#!/usr/bin/env sh

limelight -m config width 2
limelight -m config radius 10
limelight -m config placement exterior

# Blue
# limelight -m config active_color 0xff2867b9

# Green
limelight -m config active_color 0xff18ab69

limelight -m config normal_color 0x00ffffff

echo "limelight configuration loaded.."
