#!/usr/bin/env sh

# global settings
# focus window that your mouse hovers on (disabled due to right click bugs)
yabai -m config focus_follows_mouse          off
# move mouse to focused window
yabai -m config mouse_follows_focus          on
yabai -m config window_placement             second_child

# enable borders
yabai -m config window_border                on
yabai -m config window_border_blur           off
yabai -m config window_border_width          6
# yabai -m config active_window_border_color   0xcc4dd36c # Green
yabai -m config active_window_border_color   0xcc47b9fe # Blue
yabai -m config normal_window_border_color   0x00ffffff
yabai -m config insert_window_border_color   0xff1a1a1a

# no clue what this is
yabai -m config insert_feedback_color        0xffd75f5f

# Default split is 50/50
yabai -m config split_ratio                  0.50

# rebalance windows
yabai -m config auto_balance                 on

# move windows if moved with mouse
yabai -m config mouse_action1                move
# resize windows if resized with mouse
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            stack

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  5
yabai -m config bottom_padding               5
yabai -m config left_padding                 5
yabai -m config right_padding                5
yabai -m config window_gap                   10

# Rules
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
yabai -m rule --add app="^Alfred Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
yabai -m rule --add app="^Path Finder$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off
yabai -m rule --add app="^Digital Color Meter$" manage=off
yabai -m rule --add app="^zoom" manage=off
yabai -m rule --add title="^Clockify" manage=off
yabai -m rule --add app="^Authy" manage=off
yabai -m rule --add app="^Calculator" manage=off
yabai -m rule --add app="^GIMP" manage=off
yabai -m rule --add app="^DBeaver" manage=off
yabai -m rule --add app="^FromScratch" manage=off
yabai -m rule --add app="^Pritunl" manage=off
yabai -m rule --add title="ScratchPad" manage=off


# Datagrip / Rider / intelliJ
# yabai -m rule --add app="^DataGrip" manage=off
# yabai -m rule --add app="^DataGrip" title="( - )" manage=on
# Regex to match jetbrains apps
apps='^(DataGrip|JetBrains Rider)$'

# Float all JetBrains apps
yabai -m rule --add app="${apps}" manage=off

# add a signal that floats a window created by these apps when it's the only window
yabai -m signal --add event=window_created app="${apps}" action='$HOME/.config/yabai/intellij_yabai.sh'

# Teams is a massive pile of garbage
yabai -m signal --add \
    event=window_focused \
    app='^Microsoft Teams$' \
    title='^Microsoft Teams Notification$' action="yabai -m window --focus $(yabai -m query --windows | jq 'map(select(.title | endswith("Microsoft Teams")))[-1].id')"

echo "yabai configuration loaded.."

#END
